# n1 = input('Digite um valor: ')
# print(type(n1))

n1 = int(input('Digite um valor: '))
n2 = int(input('Digite outro: '))
s = (n1 + n2)
# print(type(n1))
# print('A soma entre', n1, 'e', n2, 'vale', s)
# print('A som entre {} e {} vale {}'.format(n1,n2,s))
print(f'A som entre {n1} e {n2} vale {s}')
